backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pagina"
    label: "Página Principal"
    files:
      - file: "index.html"
        label: "Contenido Principal"
        name: "contenido_principal"
        fields:
          - { label: "Título" , name: "titulo" , widgeth: "string" }
          - { label: "Título principal", name: "mainTitle", widget: "text" }
          - { label: "Descripción", name: "mainDescription", widget: "text" }
          - { label: "Imagen principal", name: "mainImage", widget: "image" }
          - { label: "Color de fondo" ,  name: "color_fondo" , widget: " color"}          - { label: "Servicios", name: "services", widget: "list", fields: [{label: "Servicio", name: "service", widget: "string"}] }
